// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCodX47i3Fet_0h_UnNn4tzLklR_IN1vok',
    appId: '1:938499828736:web:ca12640323578a24b63ce5',
    messagingSenderId: '938499828736',
    projectId: 'serenova-36443',
    authDomain: 'serenova-36443.firebaseapp.com',
    storageBucket: 'serenova-36443.firebasestorage.app',
    measurementId: 'G-HYPQLBNQD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm3fqDR5wWBySRUG3q0cfq6xRnUet2Wv8',
    appId: '1:938499828736:android:a2597ef70804d35ab63ce5',
    messagingSenderId: '938499828736',
    projectId: 'serenova-36443',
    storageBucket: 'serenova-36443.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW9gDZ2jmnzSt7WiX1J6Pj8By_MR-EKbU',
    appId: '1:938499828736:ios:ef5bc16716c1fcc3b63ce5',
    messagingSenderId: '938499828736',
    projectId: 'serenova-36443',
    storageBucket: 'serenova-36443.firebasestorage.app',
    iosBundleId: 'com.example.serenova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW9gDZ2jmnzSt7WiX1J6Pj8By_MR-EKbU',
    appId: '1:938499828736:ios:ef5bc16716c1fcc3b63ce5',
    messagingSenderId: '938499828736',
    projectId: 'serenova-36443',
    storageBucket: 'serenova-36443.firebasestorage.app',
    iosBundleId: 'com.example.serenova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCodX47i3Fet_0h_UnNn4tzLklR_IN1vok',
    appId: '1:938499828736:web:1ad4dd97f4232992b63ce5',
    messagingSenderId: '938499828736',
    projectId: 'serenova-36443',
    authDomain: 'serenova-36443.firebaseapp.com',
    storageBucket: 'serenova-36443.firebasestorage.app',
    measurementId: 'G-1ZV41ENV76',
  );

}